"""initial schema

Revision ID: 85491e23155a
Revises:
Create Date: 2026-09-22 22:43:23.454869
"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '85491e23155a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('constitution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('theme_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('protagonist_name', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=80), nullable=False),
    sa.Column('active_branch_id', sa.Uuid(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=400), nullable=False),
    sa.Column('model', sa.String(length=240), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('response_length', sa.String(length=24), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_branch_id', sa.Uuid(), nullable=True),
    sa.Column('forked_from_turn_id', sa.Uuid(), nullable=True),
    sa.Column('head_turn_id', sa.Uuid(), nullable=True),
    sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_campaign_id'), 'branches', ['campaign_id'], unique=False)
    op.create_table('campaign_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('summary_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('through_turn_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'summary_type', name='uq_branch_summary_type')
    )
    op.create_index(op.f('ix_campaign_summaries_branch_id'), 'campaign_summaries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_campaign_summaries_campaign_id'), 'campaign_summaries', ['campaign_id'], unique=False)
    op.create_table('canon_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canon_rules_branch_id'), 'canon_rules', ['branch_id'], unique=False)
    op.create_index(op.f('ix_canon_rules_campaign_id'), 'canon_rules', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_canon_rules_rule_type'), 'canon_rules', ['rule_type'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('motivations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'branch_id', 'name', name='uq_character_branch_name')
    )
    op.create_index(op.f('ix_characters_branch_id'), 'characters', ['branch_id'], unique=False)
    op.create_index(op.f('ix_characters_campaign_id'), 'characters', ['campaign_id'], unique=False)
    op.create_table('faction_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('from_faction', sa.String(length=160), nullable=False),
    sa.Column('to_faction', sa.String(length=160), nullable=False),
    sa.Column('relation', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'branch_id', 'from_faction', 'to_faction', name='uq_faction_relationship')
    )
    op.create_index(op.f('ix_faction_relationships_branch_id'), 'faction_relationships', ['branch_id'], unique=False)
    op.create_index(op.f('ix_faction_relationships_campaign_id'), 'faction_relationships', ['campaign_id'], unique=False)
    op.create_table('factions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('motives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'branch_id', 'name', name='uq_faction_branch_name')
    )
    op.create_index(op.f('ix_factions_branch_id'), 'factions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_factions_campaign_id'), 'factions', ['campaign_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('significance', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_branch_id'), 'items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_items_campaign_id'), 'items', ['campaign_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=160), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_branch_id'), 'locations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_locations_campaign_id'), 'locations', ['campaign_id'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectives_branch_id'), 'objectives', ['branch_id'], unique=False)
    op.create_index(op.f('ix_objectives_campaign_id'), 'objectives', ['campaign_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('parent_turn_id', sa.Uuid(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('player_action', sa.Text(), nullable=False),
    sa.Column('gm_response', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('in_world_time', sa.String(length=120), nullable=False),
    sa.Column('state_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_branch_id'), 'turns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_turns_campaign_id'), 'turns', ['campaign_id'], unique=False)
    op.create_table('character_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('from_character_id', sa.Uuid(), nullable=False),
    sa.Column('to_character_id', sa.Uuid(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'branch_id', 'from_character_id', 'to_character_id', name='uq_relationship_pair')
    )
    op.create_index(op.f('ix_character_relationships_branch_id'), 'character_relationships', ['branch_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_campaign_id'), 'character_relationships', ['campaign_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_branch_id'), 'checkpoints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_campaign_id'), 'checkpoints', ['campaign_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('certainty', sa.String(length=16), nullable=False),
    sa.Column('in_world_time', sa.String(length=120), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_branch_id'), 'events', ['branch_id'], unique=False)
    op.create_index(op.f('ix_events_campaign_id'), 'events', ['campaign_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('source_turn_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('in_world_time', sa.String(length=120), nullable=False),
    sa.Column('characters', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('locations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('factions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('items', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_branch_id'), 'memories', ['branch_id'], unique=False)
    op.create_index(op.f('ix_memories_campaign_id'), 'memories', ['campaign_id'], unique=False)
    op.create_table('message_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'role', 'version', name='uq_message_version')
    )
    op.create_index(op.f('ix_message_versions_turn_id'), 'message_versions', ['turn_id'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('discovered_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_turn_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_branch_id'), 'secrets', ['branch_id'], unique=False)
    op.create_index(op.f('ix_secrets_campaign_id'), 'secrets', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secrets_campaign_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_branch_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_message_versions_turn_id'), table_name='message_versions')
    op.drop_table('message_versions')
    op.drop_index(op.f('ix_memories_campaign_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_branch_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_events_campaign_id'), table_name='events')
    op.drop_index(op.f('ix_events_branch_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_checkpoints_campaign_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_branch_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_character_relationships_campaign_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_branch_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_turns_campaign_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_branch_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_objectives_campaign_id'), table_name='objectives')
    op.drop_index(op.f('ix_objectives_branch_id'), table_name='objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_locations_campaign_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_branch_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_items_campaign_id'), table_name='items')
    op.drop_index(op.f('ix_items_branch_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_factions_campaign_id'), table_name='factions')
    op.drop_index(op.f('ix_factions_branch_id'), table_name='factions')
    op.drop_table('factions')
    op.drop_index(op.f('ix_faction_relationships_campaign_id'), table_name='faction_relationships')
    op.drop_index(op.f('ix_faction_relationships_branch_id'), table_name='faction_relationships')
    op.drop_table('faction_relationships')
    op.drop_index(op.f('ix_characters_campaign_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_branch_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_canon_rules_rule_type'), table_name='canon_rules')
    op.drop_index(op.f('ix_canon_rules_campaign_id'), table_name='canon_rules')
    op.drop_index(op.f('ix_canon_rules_branch_id'), table_name='canon_rules')
    op.drop_table('canon_rules')
    op.drop_index(op.f('ix_campaign_summaries_campaign_id'), table_name='campaign_summaries')
    op.drop_index(op.f('ix_campaign_summaries_branch_id'), table_name='campaign_summaries')
    op.drop_table('campaign_summaries')
    op.drop_index(op.f('ix_branches_campaign_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('model_profiles')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
